# Generated by Django 2.2.3 on 2019-07-25 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shorturl',
            fields=[
                ('new_url_id', models.SlugField(max_length=6, primary_key=True, serialize=False)),
                ('orig_url', models.URLField(max_length=2083)),
                ('no_clicks', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='date published')),
            ],
        ),
    ]
