# Generated by Django 2.2.3 on 2019-07-30 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelinksite', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='new_url_id',
            field=models.SlugField(primary_key=True, serialize=False),
        ),
    ]
