# Generated by Django 2.2.3 on 2019-07-31 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('littlelinksite', '0002_auto_20190730_1452'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='user',
            field=models.CharField(default='', max_length=100),
        ),
    ]
