# Generated by Django 2.2.3 on 2019-08-01 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('littlelinksite', '0004_auto_20190801_0935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='littlelinksite.UserProfile'),
        ),
    ]
