# Generated by Django 2.2.3 on 2019-08-01 09:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('littlelinksite', '0005_auto_20190801_0942'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='LittleLinkUser',
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
